---
language: node_js
node_js:
  - "8"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^6.4"

install:
  - npm install

script:
  - ember test
